### ISSUE TITLE
Error issue in ModuleConnector Library in MATLAB

### ISSUE THREAD

**Issue by abrsab** [novelda/Legacy-SW#1]
I am trying to plot frame data from X2M200 sensor. I have downloaded the module connector library for matlab and placed all files in one folder (examples folder).
when I try to run file: "X2M200_lot_frame.m", I get an error saying:

The class ModuleConnector has no Constant property or Static method named 'Library'.
   
Error in X2M200_plot_frame (line 21)
Lib = ModuleConnector.Library;

Any Solution suggestion
Thank you

![error1](https://user-images.githubusercontent.com/64696212/80917203-c7b19380-8d5d-11ea-94c9-37c6947707f0.png)

**Comment by chshzh** [comment]
Did you add ModuleConnector path before running the script? The document should mention how to do this.

**Comment by abrsab** [comment]
> 
> 
> Did you add ModuleConnector path before running the script? The document should mention how to do this.



> 
> 
> Did you add ModuleConnector path before running the script? The document should mention how to do this.


If you mean adding the function "addModuleConnectorPath()" , then yes I have or it was already written in the script. 
Or do you mean that I have to manually write the path for the ModuleConnector class file?

Thank you for your reply

(I hope this picture attached could give a clear image of the situation)
![error_marks](https://user-images.githubusercontent.com/64696212/80968396-2c312900-8e18-11ea-972c-330d47d90538.jpg)

**Comment by chshzh** [comment]
I think you need to run the example in the original example folder. 
The addModuleConnectorPath function adds MC library based on this assumption.
